# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# Courtesy: https://blog.codedbyjordan.com/deploying-a-vite-app-with-github-actions

name: Candywolf CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Install Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3.3.1
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installing
        run: pnpm install

      - name: Linting
        run: pnpm lint

      - name: Testing
        run: pnpm test

      - name: Building
        run: pnpm build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0.7.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CANDYWOLF11_827A0 }}'
          channelId: live
          projectId: candywolf11-827a0
